#pragma once
// Info Service — implements octaneapi.ApiInfoService gRPC service
// Maps gRPC calls to Octane::ApiInfo SDK methods

// Forward declare — the actual generated headers come from protoc
// For now, this is a placeholder that will be filled once protos are compiled

#include <grpcpp/grpcpp.h>

// These will be generated by protoc from apiinfo.proto:
// #include "apiinfo.grpc.pb.h"

namespace OctaneServ {

// Placeholder until protos are compiled.
// Once protoc generates apiinfo.grpc.pb.h, this will inherit from
// octaneapi::ApiInfoService::Service and override the RPC methods.
//
// Key methods octaneWebR calls:
//   - octaneVersion()  → ApiInfo::octaneVersion()
//   - octaneName()     → ApiInfo::octaneName()
//   - isDemoVersion()  → ApiInfo::isDemoVersion()
//   - isSubscriptionVersion() → ApiInfo::isSubscriptionVersion()
//   - tierIdx()        → ApiInfo::tierIdx()
//   - getNodeTypes()   → ApiInfo::getNodeTypes()
//   - nodeInfo()       → ApiInfo::nodeInfo()
//   - attributeInfo()  → ApiInfo::attributeInfo()

class InfoServiceImpl {
    // Will become: public octaneapi::ApiInfoService::Service
public:
    // Placeholder — actual implementation requires compiled proto stubs
};

} // namespace OctaneServ
